### ISSUE TITLE
We should be able to specify the path of the input file as an argument

### ISSUE THREAD

**Issue by FortuneN** [RSMBrown/Mars_Rover_CSharp#1]
We should be able to specify the path of the input file as an argument.

For example, when running the application in the location ..\Mars_Rover_CSharp\Mars_Rover\bin\Debug\net6.0,
we should be able to run it using the following command line

```bat
> Mars_Rover.exe --input <path-to-input-file>
```

Example of path-to-input-file

```
C:\Users\roxy\source\repos\Mars_Rover_CSharp\Mars_Rover\input.txt
```

**Comment by RSMBrown** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/87123358/214555435-671da3f1-a2a3-4ad2-b885-d01deee1b508.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/87123358/214556316-49bf1a55-09ce-4de3-abfe-4f0e7ba8f398.png">

:P
